const baseButton = "font-ui font-extrabold text-[0.9rem] uppercase tracking-[0.08em] h-[52px] px-6 cursor-pointer border-[3px] border-ink bg-paper text-ink active:bg-ink active:text-paper disabled:cursor-not-allowed disabled:text-gray disabled:border-gray disabled:bg-paper";
export const variants = {
  card: "bg-paper border-[3px] border-ink p-6 max-[640px]:p-5",
  title: "flex items-center gap-[0.7rem] mb-5 pb-[0.9rem] border-b-[2px] border-dashed border-gray text-[0.85rem] font-extrabold uppercase tracking-[0.16em] [&>span:last-child]:ml-auto",
  icon: "grid place-items-center w-9 h-9 shrink-0 text-ink border-[2px] border-ink [&>svg]:w-5 [&>svg]:h-5 [&>svg]:stroke-[2.25]",
  badge: { base: "text-[0.72rem] font-extrabold uppercase tracking-[0.1em] px-[0.7rem] py-[0.35rem] whitespace-nowrap border-[2px] border-ink text-ink bg-paper", on: "text-paper bg-ink border-ink", off: "", online: "text-paper bg-ink border-ink", offline: "text-danger border-danger border-dashed bg-paper", hidden: "hidden" },
  button: { default: baseButton, primary: `${baseButton} bg-ink text-paper active:bg-paper active:text-ink`, danger: `${baseButton} text-paper bg-danger border-danger active:text-danger active:bg-paper`, relay: "font-ui font-extrabold text-[0.72rem] uppercase tracking-[0.08em] cursor-pointer border-[2px] border-ink bg-paper text-ink h-[38px] px-4 ml-auto" },
  controls: "flex flex-wrap gap-[0.9rem] mb-6 [&>button]:flex-1",
  phases: "flex gap-[6px] mb-6 min-h-16",
  phase: { base: "flex flex-col justify-center min-w-0 border-[2px] border-ink bg-paper text-ink py-2 px-[0.8rem] max-[640px]:py-[0.4rem] max-[640px]:px-[0.6rem]", fertigation: "bg-ink text-paper border-ink", narrow: "text-center [&>span]:hidden", label: "text-[0.66rem] font-extrabold tracking-[0.1em] uppercase overflow-hidden text-ellipsis whitespace-nowrap", value: "font-num font-extrabold text-[1.4rem] max-[640px]:text-[1.1rem] leading-[1.3] after:content-[' min'] after:font-ui after:text-[0.65rem] after:font-extrabold after:tracking-[0.06em]" },
  durations: { container: "grid gap-[0.8rem]", label: "flex items-center gap-2 text-[0.9rem] font-bold", input: "w-[5.2rem] h-[46px] ml-auto px-[0.6rem] font-num text-[1.05rem] font-extrabold text-ink text-center bg-paper border-[2px] border-ink" },
  metric: { list: "m-0", row: "flex items-baseline justify-between py-[0.6rem] border-b-[2px] border-dashed border-gray last:border-b-0", term: "text-[0.9rem] font-bold", definition: "m-0", value: "font-num font-extrabold text-[1.7rem] tabular-nums", unit: "not-italic text-[0.78rem] font-extrabold ml-[0.35rem]" },
  valve: { heading: "m-0 mb-[0.7rem] text-[0.72rem] font-extrabold uppercase tracking-[0.14em]", select: "grid grid-cols-3 gap-[6px] mb-2", button: "font-ui font-extrabold text-[0.7rem] uppercase tracking-[0.08em] cursor-pointer h-[46px] px-[0.4rem] border-[2px] border-ink bg-paper text-ink", active: "bg-ink text-paper border-ink", pending: "border-dashed", status: "m-0 mb-6 min-h-[2.4em] text-[0.68rem] font-bold leading-[1.2] tracking-[0.06em] uppercase" },
  relay: { list: "list-none m-0 p-0", row: "flex items-center gap-[0.8rem] py-[0.6rem] text-[0.95rem] font-bold border-b-[2px] border-dashed border-gray last:border-b-0", dot: "w-4 h-4 shrink-0 bg-paper border-[2px] border-ink", on: "bg-ink" },
  events: { list: "list-none m-0 p-0 text-[0.9rem] max-h-60 overflow-y-auto empty:after:content-['Nothing_yet_—_events_appear_here_as_the_system_reports_them.'] empty:after:block empty:after:py-2 empty:after:italic", row: "py-[0.4rem] border-b-[2px] border-dashed border-gray", time: "font-num tabular-nums font-extrabold mr-[0.8rem]", danger: "text-danger border-danger font-bold" },
  menu: { wrap: "relative ml-auto", trigger: "w-[42px] h-9 p-0 leading-none tracking-normal text-[1.1rem] border-[2px] border-ink bg-paper text-ink", panel: "absolute z-[2] right-0 top-[calc(100%+6px)] w-[250px] p-[0.7rem] border-[3px] border-ink bg-paper", item: "w-full h-11 px-[0.7rem] text-left border-[2px] border-ink bg-paper text-ink font-ui font-extrabold uppercase tracking-[0.08em]", reason: "min-h-[1.5em] m-[0.5rem_0_0] text-[0.72rem] font-extrabold uppercase tracking-[0.06em]" },
  dialog: { backdrop: "fixed z-10 inset-0 grid place-items-center p-4 bg-paper", panel: "w-[min(100%,480px)] p-6 border-[3px] border-ink bg-paper", title: "mb-4", text: "m-0 font-bold", status: "min-h-[1.6em] mt-4 font-bold", danger: "text-danger", actions: "flex justify-end gap-[0.8rem] mt-5 [&>button]:h-[46px]" },
} as const;
