import { parseConfig } from "./config";
import { SystemClock } from "./shared-kernel/clock";
import { UuidGenerator } from "./shared-kernel/id-generator";
import { ControllerSnapshotProjection } from "./infrastructure/projections/controller-snapshot-projection";
import { WateringIngester } from "./modules/watering/application/watering-ingester";
import { MqttDevice } from "./infrastructure/mqtt/adapter";
import { openDatabase } from "./infrastructure/db/database";
import { DrizzleWateringEventRepository } from "./modules/watering/infrastructure/drizzle-watering-event-repository";
import { DrizzleZoneRepository } from "./modules/zones/infrastructure/drizzle-zone-repository";
import { DrizzleScheduleRepository } from "./modules/scheduling/infrastructure/drizzle-schedule-repository";
import { createApp } from "./infrastructure/http/app";

const config = parseConfig(process.env);
const controller = new ControllerSnapshotProjection();
const device = new MqttDevice(config, controller);
const db = openDatabase(config.dbPath);
const zones = new DrizzleZoneRepository(db);
const wateringEvents = new DrizzleWateringEventRepository(db, zones);
const schedules = new DrizzleScheduleRepository(db);
controller.setZones(zones.all().map((zone) => ({ id: zone.id.toString(), name: zone.name.toString(), archived: zone.archived })), zones.currentAssignments().toRecord());
controller.setSchedules(schedules.all().map((entry) => ({ id: entry.id.toString(), time: entry.time.toString(), frequency: entry.frequency.toPrimitives(), channel: entry.channel.toNumber(), recipe: entry.recipe.toPrimitives() })));
new WateringIngester(wateringEvents, device).start();
const app = createApp({ device, controller, wateringEvents, zones, schedules, clock: new SystemClock(), ids: new UuidGenerator() });
app.listen(config.port, () => console.log(`Fertigation server listening on :${config.port}`));
